name: Baron
main: me.griffdragon.NewBaron.BaronCore
depend: 
version: 1.16.2
api-version: 1.16
commands:
   baron:
      description: base command
      usage: /<command>
   stats:
      description: check the stats of a player
      usage: /<command>
   class:
      description: opens class selector
      usage: /<command>